version = 1

[[analyzers]]
name = "typescript"

  [analyzers.meta]
  environment = ["browser", "nodejs", "vitest"]
  plugins = ["react"]
  run_linter = true
  run_tsc = true

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "sql"

# Optional: Falls ihr Python verwendet
[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
